### ISSUE TITLE
How do OAuth client's present one or more software statements during a dynamic registration interaction?

### ISSUE THREAD

**Issue by aviars** [HHSIDEAlab/poet#5]
Original post: @jmandel 
The README doesn't explain how a client would present one or more software statements during a dynamic registration interaction. https://tools.ietf.org/html/rfc7591 suggests that the software_statement property could be used, but this would only allow for a single endorsement (it's a single-cardinality element, not an array). It's possible we could define a convention for presenting endorsements as an "Initial Access Token" (in a header), but either of these approaches will require further specification.

Reply: @jricher:
Yes, the software statement is a single-value item and changing its cardinality would break compatibility with 7591. The initial access token has a similar issue in that there's only one, and in that case you're not guaranteed its format without further profiling (which this profile might do, claiming that it's a JWT).

There are some possible alternative approaches -- the client could present a URL that contains all of its endorsements (which that paragraph suggests it should have already), and that property could be signed by a trusted party in its own software statement separate from the endorsements. Similarly, a third party could gather all endorsements and collect them into a data structure to be defined by this specification and carried inside a single software statement. This data structure could have JWT signatures internally or hold references to hosted URLs at different providers. This latter approach was discussed in the early design reviews of the POET project.

**Comment by aviars** [comment]
@jmandel @jricher 

How about we ask the client to provide a manifest URL of endorsements that is an array?

    "endorsement_manifest_uri":    "https://example.com/.well-known/endorsement-manifest.json"

endorsement-manifest.json
----------------------------

Contains:


    [software-statement1, software-statement2, ...]

If we used such an approach, would the manifest's hostname need to be controlled by the client (e.g. DNS) ?

**Comment by jmandel** [comment]
We could; but at that point, we could just let the app pass an array of URLs each containing a single manifest :-)

**Comment by aviars** [comment]
Yes that makes sense.  What if we had additional field on top of  https://tools.ietf.org/html/rfc7591 for the purpose of endorsement?

    "endorsement_uris":  [ "https://example.com/.well-known/endorsement-manifest.json", 
    ""https://example2.com/.well-known/endorsement-manifest.json", .. ]

**Comment by jmandel** [comment]
Right -- I think that works well and stays flexible. Does an "endorsement manifest json" contain only a single endorsements for only a single client? Multiple endorsements for a single client? Multiple endorsements for multiple clients?

**Comment by aviars** [comment]
Ah yes. What should be format of an endorsement-manifest? Seems like multiple endorsements for multiple clients would allow for all use cases.  This would also make it easy for some endorsing body to publish all endorsements into a single file or do it one by one. Something like:


    {"example.com" : ["the.jwt.string", "the.jwt.string2"...]}

For this to work, must "example.com" must match the hostname in the `redirect_uri`?

**Comment by aaronmseib** [comment]
This is the flow that I had always thought about.

For a given transaction the Disclosing system needs to verify that one or more claims are true.

Before disclosing the data holder's system verifies that the claims that must be true are at the given time.

For a given transaction they may only need to verify that a single claim is true.  (Share with consumer)

For another transaction they may need to verify several claims (Consumer has authprized sharing with a 3rd Party when 3rd party is a trusted Research End point; the endpoint I am sending to is a trusted Research end point).

There may be a dozen claims that are true about the particular transaction but they are only asking about the ones that apply to the transaction that is being considered by their Policy Enforcement point at the current time.

If I am following the conversation above the question is does the Disclosing system ask about all the claims that are valid for a given transaction; only the claims that are pertinent to the given transaction (one or more in one step); ask about each of the claims one at a time until they have all the claims that they need to verify and can make the disclosure.

Which of those three are we recommending?

**Comment by aviars** [comment]
@aaronseib RE 

> Before disclosing (i.e. Approving) the data holder's system verifies that the claims that must be true are at the given time.

Claims are in the JWT. Anyone could add new data into the payload to represent "their claims". The verification, at point of approval, is the digital signature on the JWT.  I think the most basic claim we make is with the "iss" (Issuer). That's already defined for us by JWT. We should follow some standard for representing claims in JWTs where they exist. Thoughts @jricher ? 

I think you are asking about displaying claims only when they make sense for a given transaction.  I don't know how we would model that at the moment.  Can you elaborate on different transaction types?

**Comment by jmandel** [comment]
@aaronseib this sounds like a totally different set of issues (or I'm having trouble following the connection). Probably we'll want to track them in discrete GitHub issues to avoid confusion.

@aviars it might be aesier to publish a giant array rather than trying to key the entries into a dictionary (of course, you have to scan through doing O(n) work to look an entry up, but it avoids picking a key), like:

```
"all of the manifests I've got": [{
  "client_name" : "Cardiac Risk App",
  "client_uri": "https://apps-dstu2.smarthealthit.org/cardiac-risk/",
  "logo_uri" : "https://gallery.smarthealthit.org/img/apps/66.png",
 // etc"
}, {
  "client_name" : "Blood Pressure App",
  "client_uri": "https://apps-dstu2.smarthealthit.org/bp-centiles/",
  "logo_uri" : "https://gallery.smarthealthit.org/img/apps/20.png",
}]
```

If we do need to create a dict, we'll need a unique key; probably the software id is the best fit among the fields we have.

**Comment by aaronmseib** [comment]
I suspect it is a totally different set of issues.

I will refrain from confusing this thread.

**Comment by aviars** [comment]
Okay how about:


    {"manifests": [ ["the.jwt.string", "the.jwt.string2"...]}

@jmandel  The client details are plucked from the JWT so logically equivalent to what you have. I would see no reason to require a verifiable digital signature here. Any JWT would be acceptable.  This could just be a way to communicate information about an app. It would provide a means to publish information without any endorsements.

**Comment by jmandel** [comment]
@aviars I'm thinking about manifests that might be useful in additional contexts, where having the data outside of the JWT could help. Let's leave that aside for the moment though and just focus on exposing JWTs... In which case, I'm guessing your array-of-arrays is about grouping together JWTs that are "about the same app" -- which is hard to tell in general. I'd prefer *either* a flat array, or else if we want to specify a grouper (like `software_id` or `redirect_uri`) we can use a dict and just group that way like:

```
{
  "https://apps-dstu2.smarthealthit.org/bp-centiles": {
    "poet_endorsements": ["JWT1", "JWT2"]
  },
  "https://apps-dstu2.smarthealthit.org/": {
    "poet_endorsements": ["JWT3", "JWT4"]
  }
}
```

This leaves open the possibility of adding more properties later (which an array prevents).

**Comment by aviars** [comment]
@jmandel I like your way better.  No need store all of that info in JWT because it means extra parsing and harder to search.  Keying on `client_uri` makes sense. So does `software_id` and `redirect_uri`. In any case, we want to be able to group by these things. This structure allows for that.

   {
  "manifests": [{ "https://apps-dstu2.smarthealthit.org/cardiac-risk":
                  "client_name" : "Cardiac Risk App",
                  "client_uri": "https://apps-dstu2.smarthealthit.org/cardiac-risk/",
                  "logo_uri" : "https://gallery.smarthealthit.org/img/apps/66.png",
                   "software_id" : "cadiac-risk-app",
                   "redirect_uri" : ["https://apps-dstu2.smarthealthit.org/cardiac-risk/redirect"],
                  "poet_endorsements": ["JWT1", "JWT2"]},
                 {"https://apps-dstu2.smarthealthit.org/bp-centiles":
                       "client_name" : "Blood Pressure App",
                        "client_uri": "https://apps-dstu2.smarthealthit.org/bp-centiles",
                        "logo_uri" : "https://gallery.smarthealthit.org/img/apps/20.png",
                       "software_id" : "blood-pressure-app",
                       "redirect_uri" : ["https://apps-dstu2.smarthealthit.org/bp-centiles/redirect"
                      "poet_endorsements": ["JWT3", "JWT4"]},
              ]
    }

**Comment by jmandel** [comment]
I think it's still important to make sure that a key set of fields appear *inside* the JWT too, even if it's redundant...

**Comment by aviars** [comment]
@jmandel @jricher I think we agreed that it is premature to standardize a manifest, however this thread is useful and I'll be using.  Closing for now.

**Comment by aviars** [comment]
@jmandel I took your suggestion to describe the process for developers, endorsers, and data providers, break description. Please feel free open another issue or PR if there are  additional changes/suggestions.
